### ISSUE TITLE
 jq: error

### ISSUE THREAD

**Issue by dareknyckowiak** [Michaelwmx/zsh-ask#1]
What do you think is causing:
`assistant: jq: error (at <stdin>:8): Cannot iterate over null (null)`

**Comment by Licheam** [comment]
Which options did you apply causing such error? One I can trigger this bug via using invalid `ZSH_ASK_API_KEY`(or not set at the first place).
![Screenshot 2023-04-04 at 19 15 30](https://user-images.githubusercontent.com/32847549/229775155-d0d3835c-ba0c-4ed6-9f9d-edb015f21537.png)

For more detail you can turn on debug options like `ask -d`.

**Comment by dareknyckowiak** [comment]
thanks, it was `insufficient_quota`

<img width="829" alt="Screenshot 2023-04-04 at 13 36 50" src="https://user-images.githubusercontent.com/18484897/229779996-c9c13928-d984-44b5-8e90-731c3c42627a.png">

**Comment by Licheam** [comment]
You're welcome, and thank you for bringing this to my attention. I'll work on fixing it soon as I am available.

**Comment by pauldatta** [comment]
Fixed this in my fork which is AOI specific @Licheam

**Comment by dumbnose** [comment]
I'm still getting the quota limit error, even though I have plenty of quota. @pauldatta, it sounds like you fixed a bug that was causing this. Has that not made it to main in the last month?
